# This is a basic workflow to help you get started with Actions

name: CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
   if: github.ref == 'refs/heads/main'
   runs-on: [ubuntu-latest]
   steps:
     - uses: actions/checkout@v1
     - name: Push to server
       uses: appleboy/ssh-action@master
       with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
                 cd projeto
                 rm -rf *
                 git clone "https://github.com/luispereira1999/picand-go.git"
                 cd picand-go
                 docker login
                 docker stop picand-goapp
                 docker rm picand-goapp
                 docker rmi picand-go/node-web-app
                 docker build -t picand-go/node-web-app .
                 docker run -p 80:8080 --name picand-goapp -d picand-go/node-web-app
